projects/everycheese/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('everycheese.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^cheeses/', include('everycheese.cheeses.urls', namespace="cheeses")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

projects/everycheese/everycheese/cheeses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.CheeseListView.as_view(),
        name='list'
    ),

    url(
        regex=r'^(?P<slug>[\w\-]+)/$',
        view=views.CheeseDetailView.as_view(),
        name='detail'
    ),
]

projects/everycheese/everycheese/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

projects/everycheese/everycheese/cheeses/models.py
from django.db import models

from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel

class Cheese(TimeStampedModel):
    name = models.CharField("Name of Cheese", max_length=255)

    slug = AutoSlugField("Cheese Address",
        unique=True, always_update=False, populate_from="name")

    description = models.TextField("Description", blank=True)

    FIRMNESS_UNSPECIFIED = "unspecified"
    FIRMNESS_SOFT = "soft"
    FIRMNESS_SEMI_SOFT = "semi-soft"
    FIRMNESS_SEMI_HARD = "semi-hard"
    FIRMNESS_HARD = "hard"
    FIRMNESS_CHOICES = (
        (FIRMNESS_UNSPECIFIED, "Unspecified"),
        (FIRMNESS_SOFT, "Soft"),
        (FIRMNESS_SEMI_SOFT, "Semi-Soft"),
        (FIRMNESS_SEMI_HARD, "Semi-Hard"),
        (FIRMNESS_HARD, "Hard"),
    )

    firmness = models.CharField("Firmness", max_length=20,
        choices=FIRMNESS_CHOICES, default=FIRMNESS_UNSPECIFIED)

    FIRMNESS_UNSPECIFIED = "unspecified"
    FIRMNESS_SOFT = "soft"
    FIRMNESS_SEMI_SOFT = "semi-soft"
    FIRMNESS_SEMI_HARD = "semi-hard"
    FIRMNESS_HARD = "hard"
    FIRMNESS_CHOICES = (
        (FIRMNESS_UNSPECIFIED, "Unspecified"),
        (FIRMNESS_SOFT, "Soft"),
        (FIRMNESS_SEMI_SOFT, "Semi-Soft"),
        (FIRMNESS_SEMI_HARD, "Semi-Hard"),
        (FIRMNESS_HARD, "Hard"),
    )

    firmness = models.CharField("Firmness", max_length=20,
                            choices=FIRMNESS_CHOICES, default=FIRMNESS_UNSPECIFIED)


    def __str__(self):
        return self.name


# Create your models here.

projects/everycheese/everycheese/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    bio = models.TextField("Bio", blank=True)

projects/everycheese/everycheese/cheeses/views.py
from django.views.generic import ListView, DetailView
from .models import Cheese

# Create your views here.
class CheeseListView(ListView):
    model = Cheese

class CheeseDetailView(DetailView):
    model = Cheese
    template_name = 'cheeses/cheese_detail.html'

projects/everycheese/everycheese/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'bio',]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

projects/everycheese/everycheese/templates/base.html
{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}EveryCheese{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 3 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">EveryCheese</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item"><a class="nav-link" href="{% url 'cheeses:list' %}">Cheeses</a></li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 3 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
 

projects/everycheese/everycheese/templates/cheeses/cheese_detail.html
{% extends 'base.html' %}

{% block title %}Cheese: {{ cheese.name }}{% endblock title %}

{% block content %}

    <h2>{{ cheese.name }}</h2>
    
    {% if cheese.firmness %}
        <p>Firmness: {{cheese.get_firmness_display }}</p>
    {% endif %}

    {% if cheese.description %}
       <p>{{ cheese.description }}</p>
    {% endif %}

    
{% endblock content %}

projects/everycheese/everycheese/templates/cheeses/cheese_list.html
{% extends "base.html" %}

{% block title %}Cheese List{% endblock title %}

{% block content %}
    <h2>Cheese List</h2>

<ul>
    {% for cheese in cheese_list %}
    <li><a href="{% url 'cheeses:detail' cheese.slug %}">{{ cheese.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

projects/everycheese/everycheese/templates/pages/about.html
{% extends "base.html" %}

projects/everycheese/everycheese/templates/pages/home.html
{% extends "base.html" %}

projects/everycheese/everycheese/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
      {% if object.bio %}
        <p>{{ object.bio|linebreaksbr }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

projects/everycheese/everycheese/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

projects/everycheese/everycheese/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}